#!/usr/bin/python

import os
import sys

sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))

from charmhelpers.core import (
    hookenv,
    host,
)
from charmhelpers.fetch import (
    apt_install,
    apt_update,
    add_source
)

hooks = hookenv.Hooks()
log = hookenv.log

PACKAGES=['rsyslog-elasticsearch']


@hooks.hook('install')
def install():
    log('Installing rsyslog-elasticsearch')
    apt_install(packages=PACKAGES, fatal=True)


if __name__ == "__main__":
    # execute a hook based on the name the program is called by
    hooks.execute(sys.argv)
